### ISSUE TITLE
[FRONT] - Update das libs

### ISSUE THREAD

**Issue by jonatasoli** [jonatasoli/fast-ecommerce-front#209]
Rodar o comando `yarn outdated` e verificar pacotes desatualizados e fazer suas atualizações.

É necessário atualizar as bibliotecas testando todo o fluxo do carrinho seja pagamento por pix e pagamento pro cartão.

**Comment by Jpcampos123** [comment]
atualizado commit - 12c098125810d0f687f9eec5e2820a7dc23fb8d5
